trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
  PDFIUM_REVISION: '1285f619cd6ad4bdab263ce9b4b6f2599e3aa461'

jobs:
- job: Build_Pdfium
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-2019'
  steps:
  - powershell: |
      Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
      &7z x depot_tools.zip -odepot_tools
      Remove-Item depot_tools.zip
    displayName: 'Fetch depot_tools'
  - script: |
      set PATH=%cd%\depot_tools;%PATH%;
      cd depot_tools
      gclient
    displayName: 'Config depot_tools'
  - script: |
      set PATH=%cd%\depot_tools;%PATH%;
      gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
      gclient sync --revision=%PDFIUM_REVISION%
    displayName: 'Fetch Pdfium repo'
  - script: |
      set PATH=%cd%\depot_tools;%PATH%;
      cd pdfium
      ..\depot_tools\python tools\git-sync-deps
    displayName: 'Sync Pdfium deps'
  - powershell: |
      Choco install llvm 2>&1>$null
      $env:Path = "$pwd\depot_tools;" + $env:Path
      cd pdfium
      bin/gn gen out/Release_32 --args='clang_win=\"C:\Program Files\LLVM\" is_official_build=true is_component_build=false target_os=\"win\"  extra_cflags=[  \"/EHsc\", \"/Z7\" , \"/wd4291\" , \"/arch:AVX\"  ] extra_ldflags=[ \"/DEBUG:FULL\" ] target_cpu=\"x86\"' --ide=vs
      bin/gn gen out/Release_64 --args='clang_win=\"C:\Program Files\LLVM\" is_official_build=true is_component_build=false target_os=\"win\"  extra_cflags=[  \"/EHsc\", \"/Z7\" , \"/wd4291\" , \"/arch:AVX\"  ] extra_ldflags=[ \"/DEBUG:FULL\" ] target_cpu=\"x64\"' --ide=vs
    displayName: 'Setup build projects'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
      cd pdfium
      autoninja -C out\Build_64 pdfium
      autoninja -C out\Build_32 pdfium
    displayName: 'Build pdfium'
  - powershell: |
      New-Item -Name "x64" -ItemType "directory" 
      New-Item -Name "x86" -ItemType "directory"
      New-Item -Name "lib" -ItemType "directory"
      New-Item -Name "Binaries" -ItemType "directory"
      Copy-Item -Path "pdfium\out\Release_64\*.lib" -Destination "x64" -Recurse 
      Copy-Item -Path "pdfium\out\Release_64\*.dll" -Destination "x64" -Recurse 
      Copy-Item -Path "pdfium\out\Release_64\*.pdb" -Destination "x64" -Recurse 
      Copy-Item -Path "pdfium\out\Release_32\*.pdb" -Destination "x86" -Recurse 
      Copy-Item -Path "pdfium\out\Release_32\*.lib" -Destination "x86" -Recurse 
      Copy-Item -Path "pdfium\out\Release_32\*.dll" -Destination "x86" -Recurse 
      Move-Item -Path "x64" -Destination "lib"
      Move-Item -Path "x86" -Destination "lib"
      Move-Item -Path "lib" -Destination "Binaries"
      Copy-Item -Path "pdfium\include" -Destination "Binaries" -Recurse 
      7z a $(Build.ArtifactStagingDirectory)\Pdfium.zip Binaries\*
    displayName: 'Copy Binaries'
  - publish: $(Build.ArtifactStagingDirectory)/Pdfium.zip
    artifact: Pdfium Binaries

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'msmshazan''''s Github PAT'
      repositoryName: 'msmshazan/pdfiumbuild'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'Release-$(PDFIUM_REVISION)'
      title: 'Pdfium Binaries'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.ArtifactStagingDirectory)/Pdfium.zip'
