trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
  DEPOT_TOOLS_METRICS: '0'
  PYTHON_HOME: ''
  PDFIUM_REVISION: '1285f619cd6ad4bdab263ce9b4b6f2599e3aa461'

jobs:
- job: Build_Pdfium
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-2019'
  steps:
  - powershell: |
      del C:\ProgramData\Chocolatey\bin\pytho*.exe
      Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
      &7z x depot_tools.zip -odepot_tools
      Remove-Item depot_tools.zip
    displayName: 'Fetch depot_tools'
  - script: |
      set PATH=%cd%\depot_tools;%PATH%;
      cd depot_tools
      ./update_depot_tools.bat
      gclient
    displayName: 'Config depot_tools'
  - powershell: |
      $env:Path = "$pwd\depot_tools;" + $env:Path
      gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
      gclient sync --revision=%PDFIUM_REVISION%
      dir
    displayName: 'Fetch Pdfium repo'
  - script: |
      set PATH=%cd%\depot_tools;%PATH%;
      cd pdfium
    displayName: 'Sync Pdfium deps'
  - powershell: |
      Choco install llvm 2>&1>$null
      $env:Path = "$pwd\depot_tools;" + $env:Path
      cd pdfium
      gn gen out/Release_32 --args='is_clang=true is_component_build=false pdf_is_standalone=true pdf_enable_v8=true pdf_enable_xfa=true target_os=\"win\"  target_cpu=\"x86\"' 
      gn gen out/Release_64 --args='is_clang=true is_component_build=false pdf_is_standalone=true pdf_enable_v8=true pdf_enable_xfa=true target_os=\"win\"  target_cpu=\"x64\"'
    displayName: 'Setup build projects'
  - powershell: |
      $env:Path = "$pwd\depot_tools;" + $env:Path
      &("C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat")
      cd pdfium
      autoninja -C out\Release_32 pdfium
      autoninja -C out\Release_64 pdfium
    displayName: 'Build pdfium'
  - powershell: |
      New-Item -Name "x64" -ItemType "directory" 
      New-Item -Name "x86" -ItemType "directory"
      New-Item -Name "lib" -ItemType "directory"
      New-Item -Name "Binaries" -ItemType "directory"
      Copy-Item -Path "pdfium\out\Release_32\*.lib" -Destination "x86" -Recurse 
      Copy-Item -Path "pdfium\out\Release_64\*.lib" -Destination "x64" -Recurse 
      Get-ChildItem -Path "pdfium\out\Release_64\*" -Include *.lib -Recurse | Copy-Item -Destination "x64"
      Get-ChildItem -Path "pdfium\out\Release_32\*" -Include *.lib -Recurse | Copy-Item -Destination "x86"
      Move-Item -Path "x64" -Destination "lib"
      Move-Item -Path "x86" -Destination "lib"
      Move-Item -Path "lib" -Destination "Binaries"
      Copy-Item -Path "pdfium\public" -Destination "Binaries" -Recurse 
      7z a $(Build.ArtifactStagingDirectory)\Pdfium.zip Binaries\*
    displayName: 'Copy Binaries'
  - publish: $(Build.ArtifactStagingDirectory)/Pdfium.zip
    artifact: Pdfium Binaries

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'msmshazan''''s Github PAT'
      repositoryName: 'msmshazan/pdfiumbuild'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'Release-$(PDFIUM_REVISION)'
      title: 'Pdfium Binaries'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.ArtifactStagingDirectory)/Pdfium.zip'
